kind: pipeline
name: default

steps:
- name: test
  image: rust:1.44.1
  commands:
  - cd backend
  - cargo build --verbose --all
  - cargo test --verbose --all


- name: build-release
  image: rust:1.44.1
  commands:
  - cd backend
  - cargo build --release --all
  when:
    event: tag

- name: release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://gitea.ente.ninja
    files:
    - backend/target/release/snacc
  when:
    event: tag
 
