kind: pipeline
name: snacc
steps:
- name: test
  image: rust:1.44.1
  commands:
  - cd backend
  - cargo build --verbose --all
  - cargo test --verbose --all

---

kind: pipeline
name: release
when:
  event: tag
steps:
- name: build
  image: rust:1.44.1
  commands:
  - cd backend
  - cargo build --release --all

- name: publish
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://gitea.ente.ninja
    files:
    - backend/target/release/snacc
 
 ---

kind: pipeline
name: protecc
steps:
- name: docker
  image: plugins/docker
  settings:
          username:
            from_secret: docker_user
          password:
            from_secret: docker_pass
          repo: docker.cherryworm.net/protecc
          registry: docker.cherryworm.net
          auto_tag: true
