[package]
name = "snacc"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
tonic = "0.1.0-beta.1"
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
tokio = { version = "0.2.0", features = ["macros"]}
futures = { version = "0.3.1", default-features = false, features = ["alloc"]}
async-stream = "0.2.0"
pktparse = "0.4.1"
pcap-parser = {version = "0.8.2", features = ["data"]}
sled = "0.30.1"
crossbeam = "0.7.3"

[build-dependencies]
tonic-build = "0.1.0-beta.1"
