[package]
name = "snacc"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
tonic = "0.1.0-beta.1"
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
tokio = { git = "https://github.com/jxs/tokio", features = ["macros", "sync"]} # for tokio::sync::RwLock
futures = { version = "0.3.1", default-features = false, features = ["alloc"] }
async-stream = "0.2.0"
pktparse = "0.4.1"
pcap-parser = { version = "0.8.2", features = ["data"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rocksdb = "0.13.0"
metrohash = "1.0.6"
regex = "1.3.1"
derive_more = "0.99.2"
lazy_static = "1.4.0"

[build-dependencies]
tonic-build = "0.1.0-beta.1"
